#!/usr/bin/env python
""" Script to quickly investigate failed estimation runs.
"""
# standard library
import numpy as np
import sys
import os

# virtual environment
if not hasattr(sys, 'real_prefix'):
    raise AssertionError('Please use a virtual environment for testing')

# project library
sys.path.insert(0, os.environ['ROBUPY'])


# project library
from modules.auxiliary import *


# Cleanup
cleanup()

''' Request
'''


package_labels = list(range(1, 9))

development_labels = list(range(85, 103))

labels = package_labels + development_labels

for label in  list(range(101, 103)):
    print(label)

    label = str(label)
    seed = 55402

    ''' Error Reproduction
    '''
    np.random.seed(seed)

    try:
        import modules.battery as Tests
        test = getattr(Tests, 'test_' + label)
    except AttributeError:
        from robupy.tests.tests import Tests
        test = getattr(Tests, 'test_' + label)

    for _ in range(1):
        print(_)
        test()
